"use client";

import { motion } from 'framer-motion';
import { AlertTriangle } from 'lucide-react';
import Link from 'next/link';

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen w-full bg-gray-50">
      <main className="pb-24 relative z-10">
        {/* Hero Section */}
        <section className="container mx-auto px-4 py-16 lg:py-20">
          <div className="max-w-3xl mx-auto text-center">
            <motion.div
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, ease: "easeOut" }}
              className="flex items-center justify-center mb-6"
            >
              <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-primary/10 text-primary">
                <AlertTriangle className="w-8 h-8" />
              </div>
            </motion.div>
            <motion.h1
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.1, ease: "easeOut" }}
              className="text-4xl md:text-5xl font-bold text-gray-900 leading-tight mb-6"
            >
              Disclaimer
            </motion.h1>
            <motion.p
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2, ease: "easeOut" }}
              className="text-lg md:text-xl text-gray-600 max-w-2xl mx-auto mb-12"
            >
              Important information about the nature of PropWiz calculator results and the limitations of our service.
            </motion.p>
            <motion.p
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.3, ease: "easeOut" }}
              className="text-sm text-gray-500"
            >
              Last updated: May 2025
            </motion.p>
          </div>
        </section>

        {/* Disclaimer Content */}
        <section className="container mx-auto px-4 pb-16">
          <div className="max-w-4xl mx-auto">
            <motion.div
              initial={{ opacity: 0, y: 24 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.3, ease: "easeOut" }}
              className="bg-white border border-white/60 rounded-3xl shadow-md p-8 md:p-12 space-y-8"
            >
              <div>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">1. General Nature of Information</h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  The information and calculations provided by PropWiz are of a general nature only and are intended for informational and educational purposes. Nothing on this website constitutes financial, legal, taxation, or real estate advice.
                </p>
                <p className="text-gray-700 leading-relaxed">
                  PropWiz is not a licensed financial advisor, mortgage broker, conveyancer, or legal practitioner. The results generated by our calculator should not be relied upon as a substitute for professional advice tailored to your individual circumstances.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Estimates Only</h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  All figures produced by PropWiz — including but not limited to stamp duty, Lenders Mortgage Insurance (LMI), loan repayments, conveyancing costs, and government fees — are estimates only. Actual costs may differ materially from the estimates provided depending on your specific circumstances, lender policies, legal fees, and applicable government charges at the time of settlement.
                </p>
                <p className="text-gray-700 leading-relaxed">
                  We make no representation or warranty, express or implied, as to the accuracy, completeness, or fitness for purpose of any calculation or result generated by our service.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">3. Rates and Policy Changes</h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  Property-related costs in Australia are subject to frequent change. Stamp duty thresholds, first home buyer concessions, foreign investor surcharges, land tax rates, and government grant amounts are set by state and territory governments and may be amended at any time without notice.
                </p>
                <p className="text-gray-700 leading-relaxed">
                  While PropWiz makes reasonable efforts to keep our calculator current, we cannot guarantee that all figures reflect the most up-to-date rates and policies at the time of your calculation. You should verify all figures with the relevant state revenue office or a qualified professional before making any financial commitment.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">4. State and Territory Variations</h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  Property purchase costs vary significantly between Australian states and territories. Eligibility criteria for concessions, exemptions, and government grants — including the First Home Owner Grant, stamp duty exemptions, and foreign purchaser surcharges — differ by jurisdiction and are subject to change.
                </p>
                <p className="text-gray-700 leading-relaxed">
                  PropWiz uses publicly available information to model these variations. However, individual eligibility may depend on factors not captured by our calculator, and we recommend confirming your entitlements directly with the relevant authority or a licensed professional.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">5. No Professional Relationship</h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  Your use of PropWiz does not create any professional, advisory, or fiduciary relationship between you and PropWiz. We are not acting as your agent, advisor, broker, or representative in any capacity.
                </p>
                <p className="text-gray-700 leading-relaxed">
                  Any reliance you place on the results generated by our calculator is strictly at your own risk.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Seek Professional Advice</h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  Before making any property purchase decision, we strongly recommend that you seek independent advice from qualified professionals, including:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-gray-700">
                  <li>A licensed mortgage broker or lender, for loan and LMI-related costs</li>
                  <li>A conveyancer or solicitor, for legal costs, stamp duty, and settlement figures</li>
                  <li>A financial advisor, for investment structuring and tax implications</li>
                  <li>The relevant state revenue office, for confirmation of applicable duties and grants</li>
                </ul>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Limitation of Liability</h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  To the maximum extent permitted by applicable law, PropWiz and its affiliates, directors, employees, and agents will not be liable for any loss or damage — including direct, indirect, incidental, consequential, or special loss — arising out of or in connection with your use of, or reliance on, the results produced by our calculator.
                </p>
                <p className="text-gray-700 leading-relaxed">
                  This limitation applies regardless of whether such loss was foreseeable or whether PropWiz had been advised of the possibility of such loss. Nothing in this disclaimer limits any rights you may have under the Australian Consumer Law or other applicable legislation that cannot be excluded.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">8. Third Party Links</h2>
                <p className="text-gray-700 leading-relaxed">
                  PropWiz may contain links to third party websites for reference or convenience. These links do not constitute an endorsement or recommendation of any third party website or the information contained therein. PropWiz is not responsible for the accuracy, content, or privacy practices of any third party website.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">9. Changes to This Disclaimer</h2>
                <p className="text-gray-700 leading-relaxed">
                  We may update this Disclaimer from time to time to reflect changes in our service, applicable law, or best practice. The most current version will always be available on this page. Your continued use of PropWiz following any update constitutes your acceptance of the revised Disclaimer.
                </p>
              </div>

              {/* Contact Information */}
              <div className="bg-primary/10 border border-primary/20 rounded-2xl p-6 md:p-8">
                <h3 className="text-lg font-semibold text-primary mb-2">
                  Questions about this disclaimer?
                </h3>
                <p className="text-gray-700 mb-6 leading-relaxed">
                  If you have any questions about this Disclaimer, feel free to contact us.
                </p>
                <Link
                  href="/contact"
                  className="inline-flex items-center gap-2 bg-primary hover:bg-primary-focus text-secondary px-6 py-3 rounded-full font-medium transition-all duration-200 hover:shadow-lg"
                >
                  Contact Us
                </Link>
              </div>
            </motion.div>
          </div>
        </section>
      </main>
    </div>
  );
}
